var searchData=
[
  ['reference_20blas',['Reference BLAS',['../group__blas.html',1,'']]],
  ['readsparse',['ReadSparse',['../class_matrix_factory.html#ade59fcea945199cd4e096b07159c1159',1,'MatrixFactory']]],
  ['real',['real',['../group__real__matgen.html',1,'']]],
  ['real',['real',['../group__real_g_bauxiliary.html',1,'']]],
  ['real',['real',['../group__real_g_bcomputational.html',1,'']]],
  ['real',['real',['../group__real_g_bsolve.html',1,'']]],
  ['real',['real',['../group__real_g_eauxiliary.html',1,'']]],
  ['real',['real',['../group__real_g_ecomputational.html',1,'']]],
  ['real',['real',['../group__real_g_eeigen.html',1,'']]],
  ['real',['real',['../group__real_g_esing.html',1,'']]],
  ['real',['real',['../group__real_g_esolve.html',1,'']]],
  ['real',['real',['../group__real_g_tauxiliary.html',1,'']]],
  ['real',['real',['../group__real_g_tcomputational.html',1,'']]],
  ['real',['real',['../group__real_g_tsolve.html',1,'']]],
  ['real',['real',['../group__real_p_oauxiliary.html',1,'']]],
  ['real',['real',['../group__real_p_ocomputational.html',1,'']]],
  ['real',['real',['../group__real_p_osolve.html',1,'']]],
  ['real',['real',['../group__real_p_tauxiliary.html',1,'']]],
  ['real',['real',['../group__real_p_tcomputational.html',1,'']]],
  ['real',['real',['../group__real_p_tsolve.html',1,'']]],
  ['real',['real',['../group__real_s_yauxiliary.html',1,'']]],
  ['real',['real',['../group__real_s_ycomputational.html',1,'']]],
  ['real',['real',['../group__real_s_yeigen.html',1,'']]],
  ['real',['real',['../group__real_s_ysolve.html',1,'']]],
  ['reset',['reset',['../class_f_b_cache.html#a8e0d363d14c4dac6f641aa30cc50bee5',1,'FBCache::reset(int status)'],['../class_f_b_cache.html#a19625dcc982647ad0540a1bbc676cca6',1,'FBCache::reset()']]],
  ['reshape',['reshape',['../class_matrix.html#a78c9e38b32c51598d4535823c6d596f7',1,'Matrix']]],
  ['real',['real',['../group__single__blas__level1.html',1,'']]],
  ['real',['real',['../group__single__blas__level2.html',1,'']]],
  ['real',['real',['../group__single__blas__level3.html',1,'']]],
  ['real',['real',['../group__single__blas__testing.html',1,'']]],
  ['real',['real',['../group__single__eig.html',1,'']]],
  ['real',['real',['../group__single__lin.html',1,'']]]
];
