var searchData=
[
  ['complex16',['complex16',['../group__complex16__blas__level1.html',1,'']]],
  ['complex16',['complex16',['../group__complex16__blas__level2.html',1,'']]],
  ['complex16',['complex16',['../group__complex16__blas__level3.html',1,'']]],
  ['complex16',['complex16',['../group__complex16__blas__testing.html',1,'']]],
  ['complex16',['complex16',['../group__complex16__eig.html',1,'']]],
  ['complex16',['complex16',['../group__complex16__lin.html',1,'']]],
  ['complex16',['complex16',['../group__complex16__matgen.html',1,'']]],
  ['complex16',['complex16',['../group__complex16_g_bauxiliary.html',1,'']]],
  ['complex16',['complex16',['../group__complex16_g_bcomputational.html',1,'']]],
  ['complex16',['complex16',['../group__complex16_g_bsolve.html',1,'']]],
  ['complex16',['complex16',['../group__complex16_g_eauxiliary.html',1,'']]],
  ['complex16',['complex16',['../group__complex16_g_ecomputational.html',1,'']]],
  ['complex16',['complex16',['../group__complex16_g_eeigen.html',1,'']]],
  ['complex16',['complex16',['../group__complex16_g_esing.html',1,'']]],
  ['complex16',['complex16',['../group__complex16_g_esolve.html',1,'']]],
  ['complex16',['complex16',['../group__complex16_g_tcomputational.html',1,'']]],
  ['complex16',['complex16',['../group__complex16_g_tsolve.html',1,'']]],
  ['complex16',['complex16',['../group__complex16_p_oauxiliary.html',1,'']]],
  ['complex16',['complex16',['../group__complex16_p_ocomputational.html',1,'']]],
  ['complex16',['complex16',['../group__complex16_p_osolve.html',1,'']]],
  ['complex16',['complex16',['../group__complex16_p_tcomputational.html',1,'']]],
  ['complex16',['complex16',['../group__complex16_p_tsolve.html',1,'']]],
  ['complex16',['complex16',['../group__complex16_s_yauxiliary.html',1,'']]],
  ['complex16',['complex16',['../group__complex16_s_ycomputational.html',1,'']]],
  ['complex16',['complex16',['../group__complex16_s_yeigen.html',1,'']]],
  ['complex16',['complex16',['../group__complex16_s_ysolve.html',1,'']]],
  ['complex',['complex',['../group__complex__blas__level1.html',1,'']]],
  ['complex',['complex',['../group__complex__blas__level2.html',1,'']]],
  ['complex',['complex',['../group__complex__blas__level3.html',1,'']]],
  ['complex',['complex',['../group__complex__blas__testing.html',1,'']]],
  ['complex',['complex',['../group__complex__eig.html',1,'']]],
  ['complex',['complex',['../group__complex__lin.html',1,'']]],
  ['complex',['complex',['../group__complex__matgen.html',1,'']]],
  ['complex',['complex',['../group__complex_g_bauxiliary.html',1,'']]],
  ['complex',['complex',['../group__complex_g_bcomputational.html',1,'']]],
  ['complex',['complex',['../group__complex_g_bsolve.html',1,'']]],
  ['complex',['complex',['../group__complex_g_eauxiliary.html',1,'']]],
  ['complex',['complex',['../group__complex_g_ecomputational.html',1,'']]],
  ['complex',['complex',['../group__complex_g_eeigen.html',1,'']]],
  ['complex',['complex',['../group__complex_g_esing.html',1,'']]],
  ['complex',['complex',['../group__complex_g_esolve.html',1,'']]],
  ['complex',['complex',['../group__complex_g_tcomputational.html',1,'']]],
  ['complex',['complex',['../group__complex_g_tsolve.html',1,'']]],
  ['complex',['complex',['../group__complex_p_oauxiliary.html',1,'']]],
  ['complex',['complex',['../group__complex_p_ocomputational.html',1,'']]],
  ['complex',['complex',['../group__complex_p_osolve.html',1,'']]],
  ['complex',['complex',['../group__complex_p_tcomputational.html',1,'']]],
  ['complex',['complex',['../group__complex_p_tsolve.html',1,'']]],
  ['complex',['complex',['../group__complex_s_yauxiliary.html',1,'']]],
  ['complex',['complex',['../group__complex_s_ycomputational.html',1,'']]],
  ['complex',['complex',['../group__complex_s_yeigen.html',1,'']]],
  ['complex',['complex',['../group__complex_s_ysolve.html',1,'']]],
  ['computational_20routines',['Computational routines',['../group__computational_g_b.html',1,'']]],
  ['computational_20routines',['Computational routines',['../group__computational_g_e.html',1,'']]],
  ['computational_20routines',['Computational routines',['../group__computational_g_t.html',1,'']]],
  ['computational_20routines',['Computational routines',['../group__computational_p_o.html',1,'']]],
  ['computational_20routines',['Computational routines',['../group__computational_p_t.html',1,'']]],
  ['computational_20routines',['Computational routines',['../group__computational_s_y.html',1,'']]]
];
