language: cpp
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libopenblas-base
  - sudo apt-get install -y libblas-dev checkinstall
  - sudo apt-get -y install liblapack-dev checkinstall
  - sudo apt-get -y install libcppunit-dev checkinstall
