language: cpp
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libopenblas-base
  - sudo apt-get install -y libblas-dev checkinstall
  - sudo apt-get -y install liblapack-dev checkinstall
  - sudo apt-get -y install libcppunit-dev checkinstall
before_script:
  - sudo ln -s /usr/lib/openblas-base/libopenblas.a /usr/lib/;
  - mkdir -p libs
  - wget http://faculty.cse.tamu.edu/davis/SuiteSparse/SuiteSparse-4.4.6.tar.gz -O ./libs/SuiteSparse.tar.gz
  - tar xvf ./libs/SuiteSparse.tar.gz -C ./libs
  - rm -rf ./libs/SuiteSparse.tar.gz
  - cd ./libs/SuiteSparse
  - make
  - cd ../../
