language: cpp
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libopenblas-*
  - sudo apt-get install -y libblas-dev checkinstall
  - sudo apt-get -y install liblapack-dev checkinstall
  - sudo apt-get -y install libcppunit-dev checkinstall
  - sudo ln -s /usr/lib/openblas-base/libopenblas.so /usr/lib/libopenblas.so
  - sudo ln -s /usr/lib/openblas-base/libopenblas.so.0 /usr/lib/libopenblas.so.0
  - sudo ldconfig 
  - mkdir -p libs
  - wget http://faculty.cse.tamu.edu/davis/SuiteSparse/SuiteSparse-4.4.6.tar.gz -O ./libs/SuiteSparse.tar.gz
  - tar xvf ./libs/SuiteSparse.tar.gz -C ./libs
  - rm -rf ./libs/SuiteSparse.tar.gz
  - cd ./libs/SuiteSparse
  - make
  - cd ../../
  - wget http://www.netlib.org/lapack/lapack-3.6.0.tgz -O ./libs/lapack-3.6.0.tgz
  - tar zxf ./libs/lapack-3.6.0.tgz -C ./libs
  - rm ./libs/lapack-3.6.0.tgz
  - cd ./libs/lapack-3.6.0/
  - cp make.inc.example make.inc
  - cd LAPACKE
  - make
  - sudo cp ./include/lapacke.h /usr/include/
  - sudo cp ./include/lapacke_mangling.h /usr/include/
  - sudo cp ./include/lapacke_utils.h /usr/include/
  - cd ..
  - sudo cp ./liblapacke.a /usr/lib
  - cd ../../
before_script:
  - export CONFIG_FILE=config.mk
  - echo "# Auto-generated config file." > $CONFIG_FILE
  - echo -e "# Path to your SuiteSparse directory" >> $CONFIG_FILE
  - echo -e "SS_DIR = libs/SuiteSparse" >> $CONFIG_FILE
  - echo -e "# Extra headers and libraries paths" >> $CONFIG_FILE
  - echo -e "IEXTRA = /usr/include" >> $CONFIG_FILE
  - echo -e "LEXTRA = /usr/lib" >> $CONFIG_FILE
script:
  - make
  - make test
